[package]
name = "su_sqlite"
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
deadpool-sqlite.workspace = true
deadpool.workspace = true
